
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/dvormagic/ualtools
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - run: /go/src/github.com/dvormagic/ualtools/infra/circleci/deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
