
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/ualtools
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: go build -o ualtools ./cmd/ualtools
  deploy:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/ualtools
    environment:
      GOOGLE_PROJECT_ID: ual-tools
      GOOGLE_COMPUTE_ZONE: europe-west1
    steps:
      - checkout
      - run: ./infra/circleci/deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
