
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/ualtools
    steps:
      - checkout
      - run: ./infra/circleci/build.sh
      - persist_to_workspace:
          root: workspace
          paths:
            - linux/ualtools
            - mac/ualtools
            - windows/ualtools.exe
  deploy:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/ualtools
    steps:
      - checkout
      - setup_remote_docker: 
          docker_layer_caching: true
      - attach_workspace:
          at: ~/ualtools/workspace
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          ./infra/circleci/deploy.sh
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
