
FROM mysql:5.7
MAINTAINER David Vicente Ocaña Robles <dvormagic@gmail.com>

ENV MYSQL_ROOT_PASSWORD dev-root
ENV MYSQL_USER dev-user
ENV MYSQL_PASSWORD dev-password
ENV MYSQL_DATABASE default

CMD ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_bin"]
